### ISSUE TITLE
Feature request: return start and end trkpt index and data

### ISSUE THREAD

**Issue by kpricorn** [danielvogler/geopard#4]
Having the pointer to the trackpoints or the actual information returned in the geopard response would be helpful. When using for ranking  one could determine the start- and end-time of the actual effort.

Example:

```
- time
- dtw
- start_trackpoint
  - index
  - lat
  - lon
  - ele
  - time
  - ...
- end_trackpoint
  - index
  - lat
  - lon
  - ele
  - time
  - ...
```

**Comment by danielvogler** [comment]
Start and endpoint info is incorporated with 593f46b3b34a8e51923e788783d8ac287bd21c37
